// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package hubclient

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson8783fb96DecodeGithubComSignalfxGatewayHubHubclient(in *jlexer.Lexer, out *ServerResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "version":
			out.Version = string(in.String())
		case "payload":
			if in.IsNull() {
				in.Skip()
				out.Payload = nil
			} else {
				out.Payload = in.Bytes()
			}
		case "lastHeartbeat":
			out.LastHeartbeat = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8783fb96EncodeGithubComSignalfxGatewayHubHubclient(out *jwriter.Writer, in ServerResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix)
		out.String(string(in.Version))
	}
	{
		const prefix string = ",\"payload\":"
		out.RawString(prefix)
		out.Base64Bytes(in.Payload)
	}
	{
		const prefix string = ",\"lastHeartbeat\":"
		out.RawString(prefix)
		out.Int(int(in.LastHeartbeat))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ServerResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8783fb96EncodeGithubComSignalfxGatewayHubHubclient(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ServerResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8783fb96EncodeGithubComSignalfxGatewayHubHubclient(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ServerResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8783fb96DecodeGithubComSignalfxGatewayHubHubclient(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ServerResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8783fb96DecodeGithubComSignalfxGatewayHubHubclient(l, v)
}
func easyjson8783fb96DecodeGithubComSignalfxGatewayHubHubclient1(in *jlexer.Lexer, out *ServerPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
	} else {
		in.Delim('{')
		if !in.IsDelim('}') {
			*out = make(ServerPayload)
		} else {
			*out = nil
		}
		for !in.IsDelim('}') {
			key := string(in.String())
			in.WantColon()
			var v4 []uint8
			if in.IsNull() {
				in.Skip()
				v4 = nil
			} else {
				v4 = in.Bytes()
			}
			(*out)[key] = v4
			in.WantComma()
		}
		in.Delim('}')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8783fb96EncodeGithubComSignalfxGatewayHubHubclient1(out *jwriter.Writer, in ServerPayload) {
	if in == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
		out.RawString(`null`)
	} else {
		out.RawByte('{')
		v6First := true
		for v6Name, v6Value := range in {
			if v6First {
				v6First = false
			} else {
				out.RawByte(',')
			}
			out.String(string(v6Name))
			out.RawByte(':')
			out.Base64Bytes(v6Value)
		}
		out.RawByte('}')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v ServerPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8783fb96EncodeGithubComSignalfxGatewayHubHubclient1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ServerPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8783fb96EncodeGithubComSignalfxGatewayHubHubclient1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ServerPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8783fb96DecodeGithubComSignalfxGatewayHubHubclient1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ServerPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8783fb96DecodeGithubComSignalfxGatewayHubHubclient1(l, v)
}
func easyjson8783fb96DecodeGithubComSignalfxGatewayHubHubclient2(in *jlexer.Lexer, out *Server) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "payload":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Payload).UnmarshalJSON(data))
			}
		case "name":
			out.Name = string(in.String())
		case "version":
			out.Version = string(in.String())
		case "lastHeartbeat":
			out.LastHeartbeat = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8783fb96EncodeGithubComSignalfxGatewayHubHubclient2(out *jwriter.Writer, in Server) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"payload\":"
		out.RawString(prefix[1:])
		out.Raw((in.Payload).MarshalJSON())
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix)
		out.String(string(in.Version))
	}
	{
		const prefix string = ",\"lastHeartbeat\":"
		out.RawString(prefix)
		out.Int(int(in.LastHeartbeat))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Server) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8783fb96EncodeGithubComSignalfxGatewayHubHubclient2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Server) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8783fb96EncodeGithubComSignalfxGatewayHubHubclient2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Server) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8783fb96DecodeGithubComSignalfxGatewayHubHubclient2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Server) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8783fb96DecodeGithubComSignalfxGatewayHubHubclient2(l, v)
}
func easyjson8783fb96DecodeGithubComSignalfxGatewayHubHubclient3(in *jlexer.Lexer, out *RegistrationResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "lease":
			out.Lease = string(in.String())
		case "config":
			if in.IsNull() {
				in.Skip()
				out.Config = nil
			} else {
				if out.Config == nil {
					out.Config = new(Config)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.Config).UnmarshalJSON(data))
				}
			}
		case "cluster":
			if in.IsNull() {
				in.Skip()
				out.Cluster = nil
			} else {
				if out.Cluster == nil {
					out.Cluster = new(Cluster)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.Cluster).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8783fb96EncodeGithubComSignalfxGatewayHubHubclient3(out *jwriter.Writer, in RegistrationResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"lease\":"
		out.RawString(prefix[1:])
		out.String(string(in.Lease))
	}
	if in.Config != nil {
		const prefix string = ",\"config\":"
		out.RawString(prefix)
		out.Raw((*in.Config).MarshalJSON())
	}
	if in.Cluster != nil {
		const prefix string = ",\"cluster\":"
		out.RawString(prefix)
		out.Raw((*in.Cluster).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RegistrationResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8783fb96EncodeGithubComSignalfxGatewayHubHubclient3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RegistrationResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8783fb96EncodeGithubComSignalfxGatewayHubHubclient3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RegistrationResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8783fb96DecodeGithubComSignalfxGatewayHubHubclient3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RegistrationResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8783fb96DecodeGithubComSignalfxGatewayHubHubclient3(l, v)
}
func easyjson8783fb96DecodeGithubComSignalfxGatewayHubHubclient4(in *jlexer.Lexer, out *Registration) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "cluster":
			out.Cluster = string(in.String())
		case "name":
			out.Name = string(in.String())
		case "version":
			out.Version = string(in.String())
		case "payload":
			if in.IsNull() {
				in.Skip()
				out.Payload = nil
			} else {
				out.Payload = in.Bytes()
			}
		case "distributor":
			out.Distributor = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8783fb96EncodeGithubComSignalfxGatewayHubHubclient4(out *jwriter.Writer, in Registration) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"cluster\":"
		out.RawString(prefix[1:])
		out.String(string(in.Cluster))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix)
		out.String(string(in.Version))
	}
	{
		const prefix string = ",\"payload\":"
		out.RawString(prefix)
		out.Base64Bytes(in.Payload)
	}
	{
		const prefix string = ",\"distributor\":"
		out.RawString(prefix)
		out.Bool(bool(in.Distributor))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Registration) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8783fb96EncodeGithubComSignalfxGatewayHubHubclient4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Registration) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8783fb96EncodeGithubComSignalfxGatewayHubHubclient4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Registration) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8783fb96DecodeGithubComSignalfxGatewayHubHubclient4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Registration) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8783fb96DecodeGithubComSignalfxGatewayHubHubclient4(l, v)
}
func easyjson8783fb96DecodeGithubComSignalfxGatewayHubHubclient5(in *jlexer.Lexer, out *HeartbeatResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "config":
			if in.IsNull() {
				in.Skip()
				out.Config = nil
			} else {
				if out.Config == nil {
					out.Config = new(Config)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.Config).UnmarshalJSON(data))
				}
			}
		case "cluster":
			if in.IsNull() {
				in.Skip()
				out.Cluster = nil
			} else {
				if out.Cluster == nil {
					out.Cluster = new(Cluster)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.Cluster).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8783fb96EncodeGithubComSignalfxGatewayHubHubclient5(out *jwriter.Writer, in HeartbeatResponse) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Config != nil {
		const prefix string = ",\"config\":"
		first = false
		out.RawString(prefix[1:])
		out.Raw((*in.Config).MarshalJSON())
	}
	if in.Cluster != nil {
		const prefix string = ",\"cluster\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((*in.Cluster).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v HeartbeatResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8783fb96EncodeGithubComSignalfxGatewayHubHubclient5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v HeartbeatResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8783fb96EncodeGithubComSignalfxGatewayHubHubclient5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *HeartbeatResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8783fb96DecodeGithubComSignalfxGatewayHubHubclient5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *HeartbeatResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8783fb96DecodeGithubComSignalfxGatewayHubHubclient5(l, v)
}
func easyjson8783fb96DecodeGithubComSignalfxGatewayHubHubclient6(in *jlexer.Lexer, out *Config) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "budget":
			if in.IsNull() {
				in.Skip()
				out.Budget = nil
			} else {
				if out.Budget == nil {
					out.Budget = new(Budget)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.Budget).UnmarshalJSON(data))
				}
			}
		case "hb":
			out.Heartbeat = int64(in.Int64())
		case "ss":
			out.SpanSize = float64(in.Float64())
		case "ts":
			out.TraceSize = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8783fb96EncodeGithubComSignalfxGatewayHubHubclient6(out *jwriter.Writer, in Config) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Budget != nil {
		const prefix string = ",\"budget\":"
		first = false
		out.RawString(prefix[1:])
		out.Raw((*in.Budget).MarshalJSON())
	}
	{
		const prefix string = ",\"hb\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.Heartbeat))
	}
	{
		const prefix string = ",\"ss\":"
		out.RawString(prefix)
		out.Float64(float64(in.SpanSize))
	}
	{
		const prefix string = ",\"ts\":"
		out.RawString(prefix)
		out.Float64(float64(in.TraceSize))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Config) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8783fb96EncodeGithubComSignalfxGatewayHubHubclient6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Config) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8783fb96EncodeGithubComSignalfxGatewayHubHubclient6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Config) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8783fb96DecodeGithubComSignalfxGatewayHubHubclient6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Config) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8783fb96DecodeGithubComSignalfxGatewayHubHubclient6(l, v)
}
func easyjson8783fb96DecodeGithubComSignalfxGatewayHubHubclient7(in *jlexer.Lexer, out *Cluster) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "servers":
			if in.IsNull() {
				in.Skip()
				out.Servers = nil
			} else {
				in.Delim('[')
				if out.Servers == nil {
					if !in.IsDelim(']') {
						out.Servers = make([]*ServerResponse, 0, 8)
					} else {
						out.Servers = []*ServerResponse{}
					}
				} else {
					out.Servers = (out.Servers)[:0]
				}
				for !in.IsDelim(']') {
					var v12 *ServerResponse
					if in.IsNull() {
						in.Skip()
						v12 = nil
					} else {
						if v12 == nil {
							v12 = new(ServerResponse)
						}
						if data := in.Raw(); in.Ok() {
							in.AddError((*v12).UnmarshalJSON(data))
						}
					}
					out.Servers = append(out.Servers, v12)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "distributors":
			if in.IsNull() {
				in.Skip()
				out.Distributors = nil
			} else {
				in.Delim('[')
				if out.Distributors == nil {
					if !in.IsDelim(']') {
						out.Distributors = make([]*ServerResponse, 0, 8)
					} else {
						out.Distributors = []*ServerResponse{}
					}
				} else {
					out.Distributors = (out.Distributors)[:0]
				}
				for !in.IsDelim(']') {
					var v13 *ServerResponse
					if in.IsNull() {
						in.Skip()
						v13 = nil
					} else {
						if v13 == nil {
							v13 = new(ServerResponse)
						}
						if data := in.Raw(); in.Ok() {
							in.AddError((*v13).UnmarshalJSON(data))
						}
					}
					out.Distributors = append(out.Distributors, v13)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8783fb96EncodeGithubComSignalfxGatewayHubHubclient7(out *jwriter.Writer, in Cluster) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"servers\":"
		out.RawString(prefix)
		if in.Servers == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v14, v15 := range in.Servers {
				if v14 > 0 {
					out.RawByte(',')
				}
				if v15 == nil {
					out.RawString("null")
				} else {
					out.Raw((*v15).MarshalJSON())
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"distributors\":"
		out.RawString(prefix)
		if in.Distributors == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v16, v17 := range in.Distributors {
				if v16 > 0 {
					out.RawByte(',')
				}
				if v17 == nil {
					out.RawString("null")
				} else {
					out.Raw((*v17).MarshalJSON())
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Cluster) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8783fb96EncodeGithubComSignalfxGatewayHubHubclient7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Cluster) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8783fb96EncodeGithubComSignalfxGatewayHubHubclient7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Cluster) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8783fb96DecodeGithubComSignalfxGatewayHubHubclient7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Cluster) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8783fb96DecodeGithubComSignalfxGatewayHubHubclient7(l, v)
}
func easyjson8783fb96DecodeGithubComSignalfxGatewayHubHubclient8(in *jlexer.Lexer, out *Budget) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "eb":
			out.ErrorBudget = float64(in.Float64())
		case "sb":
			out.SpanBudget = float64(in.Float64())
		case "tb":
			out.TraceBudget = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8783fb96EncodeGithubComSignalfxGatewayHubHubclient8(out *jwriter.Writer, in Budget) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"eb\":"
		out.RawString(prefix[1:])
		out.Float64(float64(in.ErrorBudget))
	}
	{
		const prefix string = ",\"sb\":"
		out.RawString(prefix)
		out.Float64(float64(in.SpanBudget))
	}
	{
		const prefix string = ",\"tb\":"
		out.RawString(prefix)
		out.Float64(float64(in.TraceBudget))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Budget) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8783fb96EncodeGithubComSignalfxGatewayHubHubclient8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Budget) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8783fb96EncodeGithubComSignalfxGatewayHubHubclient8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Budget) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8783fb96DecodeGithubComSignalfxGatewayHubHubclient8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Budget) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8783fb96DecodeGithubComSignalfxGatewayHubHubclient8(l, v)
}
